-- CreateTable
CREATE TABLE "SupplyHistoryItem" (
    "id" TEXT NOT NULL,
    "financialYear" TEXT,
    "partyName" TEXT,
    "erpPartyName" TEXT,
    "itemName" TEXT NOT NULL,
    "invoiceNo" TEXT NOT NULL,
    "date" TEXT,
    "partyOrderNo" TEXT,
    "partyDate" TEXT,
    "quantity" TEXT,
    "uom" TEXT,
    "value" TEXT,
    "grossTotalInvoiceValue" TEXT,
    "lrNoDt" TEXT,
    "deliveryDestination" TEXT,
    "consigneeAddress" TEXT,
    "consigneeName" TEXT,
    "erpContractNo" TEXT,
    "erpItemCode" TEXT,
    "typeOfValve" TEXT,
    "sizeOfValve" TEXT,
    "classOfValve" TEXT,
    "sparesType" TEXT,
    "moc" TEXT,
    "orderCopy" TEXT,
    "invoice" TEXT,
    "inspectionReport" TEXT,
    "state" TEXT,
    "utility" TEXT,
    "performanceCertificate" TEXT,
    "servicePeriodComplete" TEXT,
    "warrantyValidTillAsPerContract" TEXT,
    "warrantyValidNot" TEXT,
    "bgNo" TEXT,
    "pbgValidTill" TEXT,
    "asPerOrderWarrantyPeriod" TEXT,
    "pbgClaimTill" TEXT,
    "pbgAmount" TEXT,
    "warrantyExpDateAsPerInv" TEXT,
    "partyMailAddress" TEXT,
    "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SupplyHistoryItem_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SupplyHistoryItem_invoiceNo_itemName_key" ON "SupplyHistoryItem"("invoiceNo", "itemName");
