export const CANONICAL_COLUMNS = [
  
  "ERP ITEM CODE",
  "ITEM NAME (proposed)-AUTO",
  "L1",
  "L2-VALVE TYPE",
  "L3-DIA",
  "L7-DIMENSION",
  "L4-COMPONENT",
  "L5- MATERIAL",
  "L6-STD",
   "L8 -ITEM CATEGORY",
  "UM",
  "Available Stock",
  "CONV",
  "1 pcs wgt",
  "AUM",
  "cost",
  "USD Rate Option",
  "HSN CODE",
  "HSN Code Validation",
  "CONV",
  "MAJOR MARKING",
  "NEW ITEM STATUS",
  "CURRENT STATUS",
  "RM TYPE",
  "INDIAN/IMPORTED",
];

export const STATUS_COLUMNS = new Set(["NEW ITEM STATUS", "CURRENT STATUS", "RM TYPE","INDIAN/IMPORTED" ]);
export const NUMERIC_COLUMNS = new Set(["Available Stock", "cost", "1 pcs wgt"]);

export const COL_INDEX_TO_DB_FIELD: Record<number, string> = {
  0: "erpItemCode",
  1: "itemNameAuto",
  2: "l1",
  3: "l2ValveType",
  4: "l3Dia",
  5: "l7Dimension",
  6: "l4Component",
  7: "l5Material",
  8: "l6Std",
  9: "l8ItemCategory",
  10: "um",
  11: "availableStock",
  12: "conv1",
  13: "pcsWgt",
  14: "aum",
  15: "cost",
  16: "usdRateOption",
  17: "hsnCode",
  18: "hsnCodeValidation",
  19: "conv2",
  20: "majorMarking",
  21: "newItemStatus",
  22: "currentStatus",
  23: "rmType",
  24: "indianImported",
};
