-- CreateTable
CREATE TABLE "GMDUpdateItem" (
    "id" TEXT NOT NULL,
    "erpItemCode" TEXT,
    "itemNameAuto" TEXT,
    "l1" TEXT,
    "l2ValveType" TEXT,
    "l3Dia" TEXT,
    "l7Dimension" TEXT,
    "l4Component" TEXT,
    "l5Material" TEXT,
    "l6Std" TEXT,
    "l8ItemCategory" TEXT,
    "um" TEXT,
    "conv1" TEXT,
    "pcsWgt" TEXT,
    "aum" TEXT,
    "availableStock" TEXT,
    "cost" TEXT,
    "hsnCode" TEXT,
    "conv2" TEXT,
    "majorMarking" TEXT,
    "newItemStatus" TEXT,
    "currentStatus" TEXT,
    "rmType" TEXT,
    "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GMDUpdateItem_pkey" PRIMARY KEY ("id")
);
