export const ALLOWED_OPERATION_TYPES = [
  "CAP",
  "STANDARD",
  "GB",
  "PNEUMATIC",
  "ACT",
  "ACT+GB",
  "GB/LEVER",
  "HYDRAULIC ACT",
  "WITH ISOLATION METAL SLUICE NON-RISING",
  "WITH ISOLATION RESILIENT SLUICE NON-RISING",
  "SPARES",
  "WITH ISOLATION RESILIENT SLUICE RISING",
  "WITH ISOLATION METAL SLUICE RISING",
  "WITH ISOLATION BUTTERFLY VALVE",
] as const

export const OPERATION_TYPE_DEFAULT = "STANDARD"
