export const PARTY_NAMES = [
  "Ravin Construction Co.",
  "EXCELCISOR ENGINEERING CO.",
  "CLASSIC NETWORK PVT LTD",
  "LARSEN AND TOUBRO LTD",
  "SOMBANSI ENVIRO ENGG. PVT. LIMITED.",
  "LCC Projects Limited",
  "Amrutha Constructions Private Limited",
  "KALPATARU PROJECTS INTERNATIONAL LIMITED",
  "NCC LIMITED",
  "GKC Projects Ltd",
  "GOEL PROJECTS PVT. LTD.",
  "Shapoorji Pallonji And Company Private Limited",
  "Laser Power & Infra Limited",
  "Shree Krishna Engineers",
  "KEC INTERNATIONAL LTD",
  "GA INFRA PVT LTD",
  "JSIW INFRASTRUCTURE PVT. LTD.",
  "LUMINO INDUSTRIES LIMITED",
  "JWIL Infra Ltd.",
  "YAHA WATER SYSTEMS PRIVATE LIMITED",
  "MITESH DEVELOPERS",
  "GYANSAMRUDDHI ENGINEERING AND SERVICES PRIVATE LIMITED",
  "SPML Infra Limited",
  "CIMCON SOFTWARE INDIA PVT LTD",
  "Gurumaharaj Engicon Pvt.Ltd.",
  "CAIR- ACTUATORS & VALVES",
  "LAXMI INFRA VISION PRIVATE LIMITED",
  "RAMKY INFRASTRUCTURE LIMITED",
  "BHARATIYA RESERVE BANK NOTE MUDRAN LTD",
  "Blue Star Limited",
  "VOLTEK ENGINEERING",
  "ZUBERI ENGINEERING CONSTRUCTION PVT. LTD.",
  "G K C PROJECTS LIMITED",
  "DARA ENGINEERING & INFRASTRUCTURES PRIVATE LIMITED",
  "MADHYA PRADESH POWER GENERATING COMPANY LTD",
  "URVISH R. NASIT",
  "R.C. PATEL",
  "Adiyogi Infrastructure",
  "THE WEST BENGAL POWER DEVELOPMENT CORPORATION LTD - STPS",
  "SUDHAKARA INFRATECH PRIVATE LIMITED",
  "EASTERN ELECTROLYSER LIMITED",
  "Aquaxia Water Solutions LLP",
  "Oil And Natural Gas Corporation Limited",
  "Krishna Construction Co.",
  "OFFSHORE INFRASTRUCTURES LIMITED",
  "VIKRAN ENGINEERING & EXIM PVT. LTD",
  "UMWELT ENGINEER PRIVATE LIMITED",
  "KOYA AND COMPANY CONSTRUCTION LTD",
  "MeTsi Solutions Pvt Limited",
  "Simplex Infrastructures Limited",
  "H C JAIN ENGINEERING PVT LTD",
  "PLR Projects Pvt Ltd",
  "Urban Development Department Uttar Pradesh",
  "DIVYA ENTERPRISES",
  "VA TECH WABAG LIMITED",
  "National Fertilizers Limited",
  "Kerala Water Authority",
  "South Eastern Coalfields Limited",
  "Essqube Enterprise",
  "GROMA INFRASTRUCTURE LIMITED",
  "Chandranchal Enterprise (P) Ltd",
  "KRISHANA INFRACREATIONS PRIVATE LIMITED",
  "Bharat Heavy Electricals Limited (bhel)",
  "A K PUMPS & ELECTRICALS",
  "Hindustan Traders",
  "NTPC LIMITED",
  "WILO MATHER AND PLATT PUMPS PRIVATE LIMITED",
  "MERU ENTERPRISES",
  "ALCON CONSULTING ENGINEERS (INDIA) PVT LTD",
  "GUJARAT NARMADA VALLEY FERTILIZERS",
  "POWER MECH PROJECTS LIMITED",
  "SHIVSHAKTI ENGINEERING",
  "Tahal Consulting Engineers India Private Limited",
  "Perfect Valves Pvt.Ltd.",
  "SHIVA STRUCTURES PRIVATE LIMITED",
  "Raj Infrastructure Development (India) Pvt. Ltd.",
  "AA ENGINEERS",
  "Matrushakti Sales Corporation",
  "SS Fabricators and Manufacturers Pvt Ltd",
  "Dineshchandra R Agrawal Infracon Pvt. Ltd.",
  "AMRUTHA CONSTRUCTION PVT. LTD.",
  "INSTANT PROCUREMENT SERVICES PRIVATE LIMITED",
  "PRAJAPATI MOTOR REWINDING",
  "LALIT AGARWAL",
  "MAHOT CORPORATION",
  "JVK Enterprises",
  "ARYA ENGINEERING SERVICES",
  "SUKH KARMA DISTRIBUTORS",
  "BLRS ENGINEERING AND ENERGY SERVICE PRIVATE LIMITED",
  "SURYA INTERNATIONAL ENTERPRISE PRIVATE LIMITED",
  "EXCELSIOR ENGINEERING COMPANY",
  "Omkay infraventure Pvt Ltd",
  "Aqua Chill Systems India Pvt. Ltd.",
  "GANAPATI ENTERPRISES",
  "AURO INFRA PRIVATE LIMITED",
  "SHIELD AND ALLIED",
  "Geo Miller & Co Pvt Ltd",
  "MeTsi - Solutions",
  "MAHOT CORPORATION LTD.",
  "HFCL",
  "SBE Engineering and Infrastructure Pvt. Ltd.",
  "GAJA ENGINEERING PVT LTD",
  "THERMOTECH ENGINEERS",
  "UNIVERSAL MEP Projects & Engineering Services Ltd.",
  "K.JAHANGIR BADHA",
  "MEGHA ENGINEERING & INFRASTRUCTURES LTD.",
  "OVERSEAS TRADERS",
  "Maxwell Project Private Limited",
  "GOVERNMENT EMARKETPLACE",
  "ALTAB KHAN",
  "Eastern METEC Pvt. Ltd",
  "Innovative Engineers",
  "SKYLARK Infra Engineering Pvt Ltd.",
  "S.S. Fabricators & Manufacturer Pvt Ltd.",
  "AMR Engineering Works",
  "WTE Infra Projects Pvt. Ltd.",
  "ONGC Tripura Power Company Limited",
  "Tata Projects Ltd.",
  "Vishwa Samudra Engineering Pvt Ltd",
  "Hutni Projekt FM(India) Private Limited",
  "Bharat Steel",
  "Vishnu Prakash R Punglia Limited",
  "Mecgale Pneumatics Pvt Ltd.",
  "KRISHNA CORPINDIA PRIVATE LIMITED",
  "JHABUA POWER LIMITED",
  "NLC INDIA LIMITED",
  "THE WEST BENGAL POWER DEVELOPMENT CORPORATION LTD",
  "Gujarat Water Infrastructure Ltd.",
  "Jain Irrigation",
  "Gayatri Construction Co.",
  "Khalatkar Construction Infra Pvt Ltd",
  "Rubrik Infrastructure Pvt Ltd",
  "HS Shivania Group",
  "NTPC MINING LIMITED",
  "HINDUSTAN URVARAK & RASAYAN LIMITED",
  "NMDC Steel Ltd.",
  "RASHTRIYA CHEMICALS AND FERTILIZERS LIMITED",
  "DEPARTMENT OF ATOMIC ENERGY",
  "Uttar Pradesh Cooperative Sugar Factories Federation Limited",
  "Department Of Military Affairs",
  "Nirmal Industrial Controls Pvt. Ltd.",
  "MADRAS FERTILIZERS LIMITED",
  "HINDUSTAN PETROLEUM CORPORATION LTD.",
  "SJ Environmental Solutions.",
  "Bhabha Atomic Research Centre(BARC)",
  "Damodar Valley Corporation(DVC)",
  "Uttar Pradesh Rajya Vidyut Utpadan Nigam Limited(uprvunl) Lucknow",
  "Hindustan Copper Limited",
  "Rashtriya Ispat Nigam Limited",
  "Garden Reach Ship Builders & Engineers Limited(grse)",
  "Gondwana Engineers Limited",
  "Kedia Pipes"
];
