export const UTILITIES = [
  "Ajmer Pesangam Project",
  "Amdavad Municipal Corporation",
  "Andhra Pradesh Jal Jeevan Mission (AP JJM)",
  "ANDHRA PRADESH STATE IRRIGATION DEVELOPMENT CORPORATION LIMITED",
  "Assam Urban Water Supply & Sewerage Board",
  "Bharat Petroleum Corporation Ltd",
  "BHEL, Power Sector - Project Engineering Managment",
  "Bhilai Steel Plant",
  "Chennai Metropolitan Water Supply and Sewerage Board",
  "City and Industrial Development Corporation",
  "Delhi Jal Board",
  "Department Of Atomic Energy",
  "Department of Water Resources - Government Of Odisha",
  "GUJARAT WATER SUPPLY & SEWERAGE BOARD",
  "Gujarat Industrial Development Corporation",
  "Gujarat Water Resources Development Corporation",
  "Hyderabad Metropolitan Water Supply and Sewerage Board",
  "Indian Oil Corporation Limited",
  "INDIAN RAILWAYS",
  "Irrigation & CAD Department",
  "Irrigation and CAD Department of Andhra Pradesh",
  "Jal shakti Department",
  "Karnataka Neeravari Nigam Limited: KNNL",
  "Karnataka Urban Water Supply and Drainage Board",
  "Kolkata Metropolitan Development Authority",
  "Madhya Pradesh Jal Nigam Maryadit",
  "Maharashtra Jeevan Pradhikaran",
  "Narmada and Water Resources, Water Supply and Kalpsar Department:- Government of Gujarat",
  "Narmada Valley Development Authority",
  "National Aluminium Company Limited",
  "NTPC Limited",
  "Oil And Natural Gas Corporation Limited",
  "Public Health Engineering Department(PHED) Rajasthan",
  "Rajkot Municipal Corporation",
  "Rajasthan Urban Infrastructure Development Project",
  "Rashtriya Ispat Nigam Ltd,VIZAG STEEL",
  "Rourkela Steel Plant, SAIL",
  "Rural Drinking Water and Sanitation Department",
  "Rural Water Supply & Sanitation Orissa",
  "State Water and Sanitation Mission",
  "Steel Authority Of India Limited",
  "TamilNadu Water Supply And Drainage Board Chennai",
  "Telangana State Industrial Development Corporation Limited",
  "The Fertilisers And Chemicals Travancore Limited",
  "UP Jalnigam limited",
  "Urban Administration & Development",
  "Vadodara Municipal Corporation",
  "Vidarbha Irrigation Development Corporation",
  "Visvesvaraya Jala Nigam Ltd",
  "Water Corporation of Odisha – Government of Odisha",
  "Water Resources Department",
];
